subjects_list = [
    "Mathematics", "Physics", "Chemistry", "Data Structures", "Algorithms",
    "Operating Systems", "Database Systems", "Computer Networks", "Software Engineering",
    "Machine Learning", "Artificial Intelligence", "Web Development",
    "Mobile App Development", "Cloud Computing", "Cyber Security", "Blockchain",
    "Microprocessors", "Embedded Systems", "Digital Electronics", "Control Systems",
]

skills_list = [
    "Python", "Machine Learning", "React", "Data Structures", "DBMS",
    "Blockchain", "Cyber Security", "Java", "HTML", "CSS", "JavaScript",
    "Algorithms", "Operating Systems", "Computer Networks", "Software Engineering",
    "Artificial Intelligence", "Web Development", "Mobile App Development",
    "Cloud Computing", "Microprocessors", "Embedded Systems", "Digital Electronics",
    "Control Systems",
]

project_map = {
    "Python": ["AI Chatbot", "Web Scraper", "Automation Scripts"],
    "Machine Learning": ["Stock Price Predictor", "Student Performance Analyzer"],
    "React": ["Portfolio Website", "Skill-based Recommender System"],
    "Data Structures": ["Library Management System", "Scheduling Algorithm Visualizer"],
    "DBMS": ["College Database System", "Inventory Tracker"],
    "Blockchain": ["Decentralized Voting App", "Crypto Wallet"],
    "Cyber Security": ["Vulnerability Scanner", "Secure Login System"],
    "Java": ["Bank Management System", "E-commerce Application"],
    "HTML": ["Portfolio Website", "Online Resume Builder"],
    "CSS": ["Animated Landing Page", "Responsive Blog"],
    "JavaScript": ["Interactive Quiz App", "Real-time Chat App"],
    "Algorithms": ["Pathfinding Visualizer", "Sorting Algorithm Visualizer"],
    "Operating Systems": ["Process Scheduler Simulator", "Memory Management Visualizer"],
    "Database Systems": ["E-commerce Backend", "Inventory Management System"],
    "Computer Networks": ["Packet Sniffer", "Chat Application"],
    "Software Engineering": ["Bug Tracker", "Project Management Tool"],
    "Artificial Intelligence": ["Image Classifier", "Voice Assistant"],
    "Web Development": ["Blog Platform", "Event Booking Website"],
    "Mobile App Development": ["Fitness Tracker App", "Expense Manager"],
    "Cloud Computing": ["Serverless URL Shortener", "Cloud Storage App"],
    "Microprocessors": ["Arduino Home Automation", "Sensor Data Logger"],
    "Embedded Systems": ["Smart Door Lock", "Temperature Controller"],
    "Digital Electronics": ["Logic Gate Simulator", "Digital Clock"],
    "Control Systems": ["PID Controller Simulator", "Robot Arm Control"],
}

company_map = {
    "Python": ["TCS", "Infosys", "Zoho"],
    "Machine Learning": ["Google", "Amazon", "NVIDIA"],
    "React": ["Flipkart", "Zomato", "Paytm"],
    "Data Structures": ["Microsoft", "Amazon", "Samsung"],
    "DBMS": ["Oracle", "IBM", "SAP Labs"],
    "Blockchain": ["Polygon", "CoinDCX", "Binance"],
    "Cyber Security": ["CrowdStrike", "Palo Alto Networks", "Cisco"],
    "Java": ["Wipro", "Capgemini", "Accenture"],
    "HTML": ["Freshworks", "Razorpay", "Zoho"],
    "CSS": ["Swiggy", "Meesho", "Nykaa"],
    "JavaScript": ["Dream11", "CRED", "BrowserStack"],
    "Algorithms": ["Google", "Facebook", "Amazon"],
    "Operating Systems": ["Intel", "Qualcomm", "IBM"],
    "Database Systems": ["MongoDB", "Oracle", "Microsoft"],
    "Computer Networks": ["Cisco", "Juniper", "Huawei"],
    "Software Engineering": ["Infosys", "TCS", "Accenture"],
    "Artificial Intelligence": ["OpenAI", "DeepMind", "Microsoft"],
    "Web Development": ["Shopify", "Airbnb", "Facebook"],
    "Mobile App Development": ["Google", "Apple", "Samsung"],
    "Cloud Computing": ["AWS", "Azure", "Google Cloud"],
    "Microprocessors": ["Intel", "AMD", "Texas Instruments"],
    "Embedded Systems": ["Bosch", "Honeywell", "Siemens"],
    "Digital Electronics": ["Texas Instruments", "Qualcomm", "Analog Devices"],
    "Control Systems": ["ABB", "Siemens", "Schneider Electric"],
}
